[toolchain]

[features]
resolution = true
skip-lint = false
init_if_needed = ["anchor-lang/init-if-needed"]

[programs.localnet]
prime_slot_checker = "A1TXVxKmxUYAYtZHxmPQvLt1EqbwuB2LKuXRbuLq2vsc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://xolana.xen.network:8899"
# wallet = "~/.config/solana/id.json"
wallet = "./key.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

